import Foundation
import UIKit

var iPhoneArray:[DeviceModel] = [
    
    DeviceModel(devise: .iPhone4s,
        info: "PPI: \(disctionatyPPI[.iPhone4s]!), Diagonal: \(diagonalDicrionary[.iPhone4s]!) inch",
        image: UIImage(named: "iphone4s") ?? UIImage(named: "Unknown")!),
    DeviceModel(devise: .iPhone5,
        info: "PPI: \(disctionatyPPI[.iPhone5]!), Diagonal: \(diagonalDicrionary[.iPhone5]!) inch",
        image: UIImage(named: "iphone5") ?? UIImage(named: "Unknown")!),
    DeviceModel(devise: .iPhone5s,
        info: "PPI: \(disctionatyPPI[.iPhone5s]!), Diagonal: \(diagonalDicrionary[.iPhone5s]!) inch",
        image: UIImage(named: "iphone5s") ?? UIImage(named: "Unknown")!),
    DeviceModel(devise: .iPhone5c,
        info: "PPI: \(disctionatyPPI[.iPhone5c]!), Diagonal: \(diagonalDicrionary[.iPhone5c]!) inch",
        image: UIImage(named: "iphone5c") ?? UIImage(named: "Unknown")!),
    DeviceModel(devise: .iPhone6,
        info: "PPI: \(disctionatyPPI[.iPhone6]!), Diagonal: \(diagonalDicrionary[.iPhone6]!) inch",
        image: UIImage(named: "iphone6") ?? UIImage(named: "Unknown")!),
    DeviceModel(devise: .iPhone6s,
        info: "PPI: \(disctionatyPPI[.iPhone6s]!), Diagonal: \(diagonalDicrionary[.iPhone6s]!) inch",
        image: UIImage(named: "iphone6s") ?? UIImage(named: "Unknown")!),
    DeviceModel(devise: .iPhone6Plus,
        info: "PPI: \(disctionatyPPI[.iPhone6Plus]!), Diagonal: \(diagonalDicrionary[.iPhone6Plus]!) inch",
        image: UIImage(named: "iphone6plus") ?? UIImage(named: "Unknown")!),
    DeviceModel(devise: .iPhone6sPlus,
        info: "PPI: \(disctionatyPPI[.iPhone6sPlus]!), Diagonal: \(diagonalDicrionary[.iPhone6sPlus]!) inch",
        image: UIImage(named: "iphone6splus") ?? UIImage(named: "Unknown")!),
    DeviceModel(devise: .iPhone7,
        info: "PPI: \(disctionatyPPI[.iPhone7]!), Diagonal: \(diagonalDicrionary[.iPhone7]!) inch",
        image: UIImage(named: "iphone7") ?? UIImage(named: "Unknown")!),
    DeviceModel(devise: .iPhone7Plus,
        info: "PPI: \(disctionatyPPI[.iPhone7Plus]!), Diagonal: \(diagonalDicrionary[.iPhone7Plus]!) inch",
        image: UIImage(named: "iphone7plus") ?? UIImage(named: "Unknown")!),
    DeviceModel(devise: .iPhone8,
        info: "PPI: \(disctionatyPPI[.iPhone8]!), Diagonal: \(diagonalDicrionary[.iPhone8]!) inch",
        image: UIImage(named: "iphone8") ?? UIImage(named: "Unknown")!),
    DeviceModel(devise: .iPhone8Plus,
        info: "PPI: \(disctionatyPPI[.iPhone8Plus]!), Diagonal: \(diagonalDicrionary[.iPhone8Plus]!) inch",
        image: UIImage(named: "iphone8plus") ?? UIImage(named: "Unknown")!),
    //
    DeviceModel(devise: .iPhoneX,
        info: "PPI: \(disctionatyPPI[.iPhoneX]!), Diagonal: \(diagonalDicrionary[.iPhoneX]!) inch",
        image: UIImage(named: "iphoneX") ?? UIImage(named: "Unknown")!),
    DeviceModel(devise: .iPhoneXS,
        info: "PPI: \(disctionatyPPI[.iPhoneXS]!), Diagonal: \(diagonalDicrionary[.iPhoneXS]!) inch",
        image: UIImage(named: "iphoneXs") ?? UIImage(named: "Unknown")!),
    DeviceModel(devise: .iPhoneXSMax,
        info: "PPI: \(disctionatyPPI[.iPhoneXSMax]!), Diagonal: \(diagonalDicrionary[.iPhoneXSMax]!) inch",
        image: UIImage(named: "iphoneXsmax") ?? UIImage(named: "Unknown")!),
    DeviceModel(devise: .iPhoneXR,
        info: "PPI: \(disctionatyPPI[.iPhoneXR]!), Diagonal: \(diagonalDicrionary[.iPhoneXR]!) inch",
        image: UIImage(named: "iphoneXr") ?? UIImage(named: "Unknown")!)
]

var iPadArray: [DeviceModel] = [
    DeviceModel(devise: .iPad5gen,
        info: "PPI: \(disctionatyPPI[.iPad5gen]!), Diagonal: \(diagonalDicrionary[.iPad5gen]!) inch",
        image: UIImage(named: "ipad5gen") ?? UIImage(named: "Unknown")!),
    DeviceModel(devise: .iPad6gen,
        info: "PPI: \(disctionatyPPI[.iPad6gen]!), Diagonal: \(diagonalDicrionary[.iPad6gen]!) inch",
        image: UIImage(named: "ipad6gen") ?? UIImage(named: "Unknown")!),
    DeviceModel(devise: .iPadAir3gen,
        info: "PPI: \(disctionatyPPI[.iPadAir3gen]!), Diagonal: \(diagonalDicrionary[.iPadAir3gen]!) inch",
        image: UIImage(named: "ipadAir3gen") ?? UIImage(named: "Unknown")!),
    DeviceModel(devise: .iPadMini,
        info: "PPI: \(disctionatyPPI[.iPadMini]!), Diagonal: \(diagonalDicrionary[.iPadMini]!) inch",
        image: UIImage(named: "ipadMini") ?? UIImage(named: "Unknown")!),
    DeviceModel(devise: .iPadMini2,
        info: "PPI: \(disctionatyPPI[.iPadMini2]!), Diagonal: \(diagonalDicrionary[.iPadMini2]!) inch",
        image: UIImage(named: "ipadMini2") ?? UIImage(named: "Unknown")!),
    DeviceModel(devise: .iPadMini3,
        info: "PPI: \(disctionatyPPI[.iPadMini3]!), Diagonal: \(diagonalDicrionary[.iPadMini3]!) inch",
        image: UIImage(named: "ipadMini3") ?? UIImage(named: "Unknown")!),
    DeviceModel(devise: .iPadMini4,
        info: "PPI: \(disctionatyPPI[.iPadMini4]!), Diagonal: \(diagonalDicrionary[.iPadMini4]!) inch",
        image: UIImage(named: "ipadMini4") ?? UIImage(named: "Unknown")!),
    DeviceModel(devise: .iPadMini5,
        info: "PPI: \(disctionatyPPI[.iPadMini5]!), Diagonal: \(diagonalDicrionary[.iPadMini5]!) inch",
        image: UIImage(named: "ipadMini5") ?? UIImage(named: "Unknown")!),
   
    DeviceModel(devise: .iPadPro,
        info: "PPI: \(disctionatyPPI[.iPadPro]!), Diagonal: \(diagonalDicrionary[.iPadPro]!) inch",
        image: UIImage(named: "ipadPro") ?? UIImage(named: "Unknown")!),
    DeviceModel(devise: .iPadPro10,
        info: "PPI: \(disctionatyPPI[.iPadPro10]!), Diagonal: \(diagonalDicrionary[.iPadPro10]!) inch",
        image: UIImage(named: "ipadPro10") ?? UIImage(named: "Unknown")!),
    DeviceModel(devise: .iPadPro11,
        info: "PPI: \(disctionatyPPI[.iPadPro11]!), Diagonal: \(diagonalDicrionary[.iPadPro11]!) inch",
        image: UIImage(named: "ipadPro11") ?? UIImage(named: "Unknown")!),
    DeviceModel(devise: .iPad12_1gen,
        info: "PPI: \(disctionatyPPI[.iPad12_1gen]!), Diagonal: \(diagonalDicrionary[.iPad12_1gen]!) inch",
        image: UIImage(named: "ipadPro12.1gen") ?? UIImage(named: "Unknown")!),
    DeviceModel(devise: .iPad12_2gen,
        info: "PPI: \(disctionatyPPI[.iPad12_2gen]!), Diagonal: \(diagonalDicrionary[.iPad12_2gen]!) inch",
        image: UIImage(named: "ipadPro12.2gen") ?? UIImage(named: "Unknown")!),
    DeviceModel(devise: .iPad12_3gen,
        info: "PPI: \(disctionatyPPI[.iPad12_3gen]!), Diagonal: \(diagonalDicrionary[.iPad12_3gen]!) inch",
        image: UIImage(named: "ipadPro12.3gen") ?? UIImage(named: "Unknown")!),
    
]

var allDevices:[DeviceModel] = iPhoneArray + iPadArray
